### ISSUE TITLE
PEP8 coding style

### ISSUE THREAD

**Issue by petrbel** [farizrahman4u/qlearning4k#2]
Hi,
I noticed that the spaces are used (as the way of indentation) instead of spaces. My PyCharm cries a lot as it isn't PEP8-standard compatible.

Would you accept my pull-request if I transformed the code so that it becomes correctly styled according to PEP8? Besides the space/tab problem, I'd love to add/remove blank lines. I believe it would help other developers to work with your code as it is the commonly required standard.

Btw great code, I'm looking forward to play with it more!

Regards
Petr

**Comment by farizrahman4u** [comment]
Cool!
