### ISSUE TITLE
IndexError: too many indices for array 

### ISSUE THREAD

**Issue by korymath** [farizrahman4u/qlearning4k#3]
Running into an issue running the test example programs.

Korys-MacBook-Air:examples korymathewson$ python test_snake.py 
Using Theano backend.
Traceback (most recent call last):
  File "test_snake.py", line 23, in <module>
    agent.train(snake, batch_size=64, nb_epoch=10000, gamma=0.8)
  File "build/bdist.macosx-10.6-intel/egg/qlearning4k/agent.py", line 92, in train
IndexError: too many indices for array

Not 100% sure what the error is, before I started digging in I thought I would post some details.

**Comment by farizrahman4u** [comment]
Fixed.

**Comment by farizrahman4u** [comment]
Fixed.
